title: "Shimanta Bhuyan | Freelance Full Stack Web Developer"
author: Shimanta Bhuyan
email: bhuyanshimanta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Shimanta Bhuyan, an aspiring Full Stack Web Developer.
  I have been freelancing for the past 6 months and learning 
  new technologies to develop websites.

# social links
github_username:  ShimantaBhuyan
linkedin_username: shimantabhuyan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
